### ISSUE TITLE
Ideas: Is is good to make PR for every commit?

### ISSUE THREAD

**Issue by shinevue** [Finalgoal231/finalGoal#15]
### Discussed in https://github.com/orgs/Finalgoal231/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **shinevue** July  4, 2024</sup>
Discussion is started.</div>

**Comment by creative2113** [comment]
yes, I think so.
it is because that makes the project to be correct, and we can easily handle a bit error.
also it is suitable for our development rule.
how about you?

**Comment by creative2113** [comment]
why don't you close this issue.
I have already solved this issue.

**Comment by shinevue** [comment]
Wait other's opinion

**Comment by creative2113** [comment]
I see

**Comment by joellake992** [comment]
It will be discussed win discussion ground

**Comment by creative2113** [comment]
I can handle this problem.
please hire me.
