### ISSUE TITLE
There isn't any command to run concurrently

### ISSUE THREAD

**Issue by shinevue** [Finalgoal231/finalGoal#18]
There isn't any command to run concurrently

_Originally posted by @Johnhvy in https://github.com/Finalgoal231/finalGoal/pull/17#discussion_r1685743395_

**Comment by shinevue** [comment]
I think that to run project with one command like 
`npm run dev`
but deploy this project it need to run only frontend
Make sence?

**Comment by Johnhvy** [comment]
Ok
No problem
I approve your changes
