### ISSUE TITLE
Issue: Responsive of category add component in changing profile information

### ISSUE THREAD

**Issue by shinevue** [Finalgoal231/finalGoal#6]
Now in profile setting page, categories form seem to not be related add category select form.
Let's discuss this issue and push correct code.

**Comment by shinevue** [comment]
Hello, everyone.
New Issue is created.
Please answer.

**Comment by mcyandex** [comment]
Yeah, after checking, I will correct it.

**Comment by shinevue** [comment]
Sorry, I fixed and then merged it.
This issue is solved.

**Comment by oddcommitking** [comment]
I checked and approve it.
