### ISSUE TITLE
Please help me!!!

### ISSUE THREAD

**Issue by creative2113** [Finalgoal231/finalGoal#84]
### Discussed in https://github.com/orgs/Finalgoal231/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **Suzuki0916** August 22, 2024</sup>
I'm trying to change the email for the project to something else.
However, when I change and edit the email, no other errors occur, but when I try to change the email after editing it, it doesn't work properly.
I'll upload the error contents as a picture.
![Capture](https://github.com/user-attachments/assets/491b5178-c8f6-43fc-a5f5-523dafd9d68a)
</div>

**Comment by shinevue** [comment]
There was some files at change state.
First commit before convert
